[project]
name = "marimo-template"
version = "0.1.0"
description = "Template for marimo repositories"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.23.8",
    "poethepoet>=0.38.0",
    "matplotlib>=3.8.0",
    "pyomo>=6.0.0",
    "seaborn>=0.12.0",
    "scikit-learn>=1.8.0",
    "openpyxl>=3.1.5",
    "highspy>=1.14.0",
    "requests>=2.34.2",
]
[tool.poe.tasks]
notebook = "marimo edit notebooks"
